az2                 = "us-west-2a"
subnet-suffix       = "a" 
role2               = "kafka_broker_node"
purpose2            = "kafka_broker_node"
region              = "us-west-2"
inboundport         = "9092"
machine-ami         = "kafka_linux_ami_agent"
