az2                 = "us-east-1a"
subnet-suffix       = "a" 
role2               = "kafka-broker-node"
purpose2            = "kafka-broker-node"
region              = "us-east-1"
inboundport         = "9092"
machine-ami         = "my-linux-ami"
