az2                 = "us-east-1c"
subnet-suffix       = "c" 
role2               = "kafka-zookeeper-node"
purpose2            = "kafka-zookeeper-node"
region              = "us-east-1"
inboundport         = "2081"
machine-ami         = "my-linux-ami"
