az2                 = "us-west-2c"
subnet-suffix       = "c" 
role2               = "kafka_zookeeper_node"
purpose2            = "kafka_zookeeper_node"
region              = "us-west-2"
inboundport         = "2081"
machine-ami         = "kafka_linux_ami_agent"
